import { createHash } from 'node:crypto';
import { mkdir, open, unlink, type FileHandle } from 'node:fs/promises';
import { join, relative, resolve } from 'node:path';
import { CONFIG_SCHEMA_VERSION, type Config, type InputItem } from './config.js';

export const STARTER_CONFIG_FILENAME = 'dailies.config.json';
export const STARTER_INPUTS_FILENAME = 'dailies.cases.jsonl';

const STARTER_ITEMS: InputItem[] = [
  {
    id: 'greeting',
    input: 'hello',
    baseline_label: 'pass',
    baseline_output: 'hello',
  },
  {
    id: 'summary',
    input: 'summarize this',
    baseline_label: 'pass',
    baseline_output: 'summarize this',
  },
  {
    id: 'support',
    input: 'reset password',
    baseline_label: 'pass',
    baseline_output: 'reset password',
  },
];

export interface InitializeResult {
  directory: string;
  configPath: string;
  inputsPath: string;
  nextCommand: string;
}

function sha256Digest(bytes: string): string {
  return `sha256:${createHash('sha256').update(bytes).digest('hex')}`;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function nextConfigArgument(configPath: string): string {
  const pathFromCwd = relative(process.cwd(), configPath) || STARTER_CONFIG_FILENAME;
  return shellQuote(pathFromCwd);
}

async function closeQuietly(handle: FileHandle | undefined): Promise<void> {
  if (handle === undefined) return;
  await handle.close().catch(() => undefined);
}

async function unlinkQuietly(path: string, created: boolean): Promise<void> {
  if (!created) return;
  await unlink(path).catch(() => undefined);
}

function existingFileError(error: unknown, fallbackPath: string): Error {
  const fsError = error as NodeJS.ErrnoException;
  if (fsError.code !== 'EEXIST') {
    return error instanceof Error ? error : new Error(String(error));
  }
  const path = typeof fsError.path === 'string' ? fsError.path : fallbackPath;
  return new Error(`refusing to overwrite existing file: ${path}`, { cause: error });
}

/** Create a deterministic, runnable schema-v4 starter without overwriting user files. */
export async function initializeDailiesProject(
  targetDirectory: string = '.',
): Promise<InitializeResult> {
  const directory = resolve(targetDirectory);
  const inputsPath = join(directory, STARTER_INPUTS_FILENAME);
  const configPath = join(directory, STARTER_CONFIG_FILENAME);
  const inputsBytes = STARTER_ITEMS.map((item) => JSON.stringify(item)).join('\n') + '\n';
  const config: Config = {
    schemaVersion: CONFIG_SCHEMA_VERSION,
    inputs: {
      type: 'jsonl',
      path: STARTER_INPUTS_FILENAME,
      digest: sha256Digest(inputsBytes),
    },
    scope: {
      id: 'starter-regression-corpus-v1',
      kind: 'regression_corpus',
      expectedItems: STARTER_ITEMS.length,
      collectionProcedure: 'Demonstration cases generated by dailies init; replace before use.',
      population: 'Only the three generated starter behaviors.',
      timeWindow: {
        kind: 'not_applicable',
        reason: 'This is a static demonstration corpus.',
      },
    },
    candidate: {
      type: 'command',
      template: 'printf %s {input}',
    },
    judge: { type: 'exact-match' },
    thresholds: {
      minPassRate: 1,
      maxRegressions: 0,
    },
    trustPolicy: {
      admissibleClasses: ['deterministic'],
    },
    concurrency: 2,
    timeoutMs: 10_000,
    output: { dir: 'dailies-out' },
  };
  const configBytes = JSON.stringify(config, null, 2) + '\n';

  await mkdir(directory, { recursive: true });

  let inputsHandle: FileHandle | undefined;
  let configHandle: FileHandle | undefined;
  let inputsCreated = false;
  let configCreated = false;
  try {
    inputsHandle = await open(inputsPath, 'wx');
    inputsCreated = true;
    configHandle = await open(configPath, 'wx');
    configCreated = true;

    await inputsHandle.writeFile(inputsBytes, 'utf8');
    await configHandle.writeFile(configBytes, 'utf8');
    await Promise.all([inputsHandle.close(), configHandle.close()]);
    inputsHandle = undefined;
    configHandle = undefined;
  } catch (error) {
    await Promise.all([closeQuietly(inputsHandle), closeQuietly(configHandle)]);
    await Promise.all([
      unlinkQuietly(inputsPath, inputsCreated),
      unlinkQuietly(configPath, configCreated),
    ]);
    throw existingFileError(error, inputsCreated ? configPath : inputsPath);
  }

  return {
    directory,
    configPath,
    inputsPath,
    nextCommand: `npx dailies --config ${nextConfigArgument(configPath)}`,
  };
}
